import express from "express";
import multer from "multer";
import { getProducts, addProduct } from "../controllers/productController.js";

// Configurazione Multer per conservare il file temporaneamente in memoria RAM
const upload = multer({ storage: multer.memoryStorage() });

const router = express.Router();

/**
 * @openapi
 * /api/products:
 *   get:
 *     summary: Get the list of all products
 *     tags:
 *       - Products
 *     responses:
 *       '200':
 *         description: List of products successfully recovered
 *         content:
 *           application/json:
 *             schema:
 *               type: array
 *               items:
 *                 type: object
 *                 properties:
 *                   _id:
 *                     type: string
 *                     example: "65f2c1234567890abcdef123"
 *                   name:
 *                     type: string
 *                     example: "Pro Tennis Racket"
 *                   description:
 *                     type: string
 *                     example: "Lightweight racket for intermediate players."
 *                   price:
 *                     type: number
 *                     example: 40
 *                   imageURL:
 *                     type: string
 *                     example: "https://kinetixstore.blob.core.windows.net/product-images/racket.jpg"
 *                   tags:
 *                     type: array
 *                     items:
 *                       type: string
 *                     example:
 *                       - tennis
 *                       - racket
 *                       - outdoor
 *       '500':
 *         description: Error within server
 *
 *   post:
 *     summary: Create new product with AI Auto-Tagging & Image Upload
 *     description: Create a product by providing details and either a file upload or an imageURL. Tags are automatically generated by Azure AI.
 *     tags:
 *       - Products
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             required:
 *               - name
 *               - description
 *               - price
 *             properties:
 *               name:
 *                 type: string
 *                 example: "Official Match Basketball"
 *               description:
 *                 type: string
 *                 example: "Heavy duty leather basketball engineered for indoor matches."
 *               price:
 *                 type: number
 *                 example: 29
 *               image:
 *                 type: string
 *                 format: binary
 *                 description: Image file to upload to Azure Blob Storage
 *               imageURL:
 *                 type: string
 *                 example: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Basketball.png"
 *                 description: Fallback external image URL (if no file is uploaded)
 *     responses:
 *       '201':
 *         description: Product successfully created with automated tags
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 message:
 *                   type: string
 *                   example: "New product created."
 *                 product:
 *                   type: object
 *                   properties:
 *                     _id:
 *                       type: string
 *                     name:
 *                       type: string
 *                     description:
 *                       type: string
 *                     price:
 *                       type: number
 *                     imageURL:
 *                       type: string
 *                     tags:
 *                       type: array
 *                       items:
 *                         type: string
 *                       example:
 *                         - basketball
 *                         - ball
 *                         - playground
 *       '400':
 *         description: Input data is invalid
 *       '500':
 *         description: Error within server
 */

router.route("/").get(getProducts).post(upload.single("image"), addProduct);

export default router;
